### ISSUE TITLE
Modificaciones del apartado "Gestión del código fuente" de la wiki

### ISSUE THREAD

**Issue by antnolang** [decide-dialga/decide#12]
Se solicitan los siguientes cambios en el apartado de "Gestión de código fuente" de la wiki:
* Definir cuándo deben hacerse los merge desde las ramas de equipo a develop y desde develop a master.
* Aclarar si deben eliminarse las ramas feature subidas en el repositorio y cuándo.
* Una vez que se integra todo en develop y se solucionan los conflictos, se hace un merge a master. Una vez tengamos una versión funcional en master, debe hacerse otro merge a las ramas de equipo para tener los últimos cambios añadidos antes de seguir trabajando. Definir cuándo deben hacerse estos merge, quién los debe hacer, etc.
* Puede ser interesante utilizar las etiquetas de voting, auth, census, etc. también para los pull-request.
* Aclarar cuál debe ser el formato de nombre de las ramas feature.
* Aclarar qué pasa cuando un pull request no pasa alguna de las revisiones.

Se solicitan estos cambios, no solo para tener la documentación necesaria para la asignatura, sino también para tener claramente definido los procesos y homogeneizar la forma de trabajar.

Para el nombre de las ramas feature propongo el mismo formato de nombre que se propone en git flow.

**Comment by antnolang** [comment]
A las modificaciones solicitadas anteriormente añado la siguiente:
* Definir cuando se asigna a los revisores en los pull requests

**Comment by CavernaryBeast** [comment]
Mantuvimos una reunión en la que comentamos todos los puntos aquí mencionados. 
El acta de reunión puede verse en el [[Dialga]Diario de trabajo de los coordinadores](https://github.com/decide-dialga/decide/wiki/%5BDialga%5D-Diario-de-trabajo-de-coordinadores).

Por tanto, esta incidencia puede darse por resuelta.
