### ISSUE TITLE
Conflicto encontrado al revisar Pull Request Vis->Develop

### ISSUE THREAD

**Issue by ferruipli** [decide-dialga/decide#126]
Ambos revisores comprobando los cambios realizados que se describen en el Pull Request #122 observan que existen diversos conflictos en los siguientes archivos:

- decide/authentication/urls.py
- decide/decide/settings.py
- decide/static/css/styles.css
- decide/templates/account/login.html
- decide/templates/account/logout.html
- decide/templates/base.html
- decide/templates/navbar.html
- requirements.txt

Puede ser que tras hacerse un merge a develop no se hayan traido los cambios de dicha rama a la rama vis haciendo que salten conflictos ahora al querer realizar cambios sobre los anteriores archivos.

**Comment by serortagu** [comment]
Cierro la issue tras la solución aportada en el [comentario del pull-request ](https://github.com/decide-dialga/decide/pull/122#issuecomment-573338989).
