### ISSUE TITLE
Build erróneo en Travis tras mergear Pull Request auth->develop

### ISSUE THREAD

**Issue by ferruipli** [decide-dialga/decide#130]
Se ha observado que tras hacer el mergeo de la rama `auth` a `develop` no se han pasado las comprobaciones de Travis al causar fallo el siguiente test: `test_fake_signin (authentication.testSelenium.TestSignin)`

Esta incidencia repercute a la hora de querer aceptar el Pull Request #122 

La solución a esta issue sería:

1. Actualizar la rama develop para traerse los últimos cambios.
2. Una vez actualizada, realizar la modificación necesaria en dicho test.
3. Volver a ejecutar todos los test pertenecientes al subsistema auth.
4. En caso de éxito de dichos tests, realizar el commit con los cambios.

**Comment by CavernaryBeast** [comment]
Ya ha sido resuelto el problem causado en la Pull-Request #122 . Allí podemos ver en los comentarios todo lo necesario.
