### ISSUE TITLE
Separar la documentación común en distintos archivos.

### ISSUE THREAD

**Issue by serortagu** [decide-dialga/decide#23]
Se debe separar la documentación de **[Dialga] Documentación común del proyecto** en archivos independientes para una mejor organización. Para ello se deben crear cinco nuevo documentos:

- Home. @serortagu 
- Gestión de incidencias. @serortagu 
- Gestión del código. @antnolang 
- Gestión de la construcción e integración continua. @serortagu 
- Gestión de liberaciones, despliegue y entregas. @antnolang

**Comment by serortagu** [comment]
Documentos Home, Gestión de incidencias y Gestión de la construcción e integración continua creados,

**Comment by antnolang** [comment]
Documentos Gestión del código y Gestión de liberaciones, despliegue y entregas creados

**Comment by antnolang** [comment]
Propongo que en la página de Home de la wiki, se sustituya el concepto representante por coordinador, ya que es el concepto exacto que se usa en la normativa de la asignatura y de esta forma se pueden evitar malos entendidos por parte del profesorado.

**Comment by serortagu** [comment]
@antnolang pienso lo mismo. Cambio realizado en la página home y doy por concluída la issue.
