### ISSUE TITLE
Arreglar errores de Travis para proceder al merge hacia develop

### ISSUE THREAD

**Issue by pedroswe** [decide-dialga/decide#51]
Para realizar el merge es necesario que las features pasen los tests de Travis.
Se adjunta los links directos a los builds de travis-ci:
- [continuous-integration/travis-ci/pr](https://travis-ci.org/decide-dialga/decide/builds/632388164?utm_source=github_status&utm_medium=notification)
- [continuous-integration/travis-ci/push](https://travis-ci.org/decide-dialga/decide/builds/632386477?utm_source=github_status&utm_medium=notification)

Es posible que haya habido cambios en el domino y no se hayan corregido las migraciones.

**Comment by fraguerrero** [comment]
Ya se han corregido los tests que desencadenaban los problemas para hacer el build en Travis. Básicamente se han actualizado referencias del modelo anterior User para reemplazarlas por el nuevo modelo CustomUser.

Link del build en Travis con push de los cambios:

[continuous-integration/travis-ci/push](https://travis-ci.org/decide-dialga/decide/builds/632632487?utm_medium=notification&utm_source=github_status)
