### ISSUE TITLE
Estilo CSS demasiado intrusivo.

### ISSUE THREAD

**Issue by serortagu** [decide-dialga/decide#53]
Se ha detectado que el estilo creado para la página de inicio de sesión `decide/static/css/styles.css` es demasiado intrusivo. Se modifica clases propias de Bootstrap que alteran el uso de Bootstrap en otros subsistemas como Visualizer.

Algunos ejemplos son:
![Captura-issue-style](https://user-images.githubusercontent.com/36485209/71758594-3232ef80-2ea2-11ea-9666-c26fcbeb2f75.PNG)

Esta clase pondrá ese estilo a todos los elementos HTML que utilicen la clase `.card`.

**Por lo tanto se proponen las siguientes soluciones:**
1. Utilizar nombres de clases propios, teniendo que modificar gran parte de este archivo de estilo CSS. 

2. Importar este estilo CSS solo en la `template` de la página de inicio de sesión o aquellas donde se utilice, para que no altere el estilo en aquellas vista donde no se utilice. **Se considera que esta solución es más viable que la anterior.**

**Comment by CavernaryBeast** [comment]
He publicado un Commit en la rama auth-feature/extend-email-signup. Los cambios hechos no han sido testeados aún debido a que no dispongo de un sistema en el que poder probarlos. En cuanto disponga de él, se harán las pruebas pertinentes y si el error se ha solucionado se cerrará este Issue.

**Comment by CavernaryBeast** [comment]
Los cambios ya han sido testeados, se han corregido con el último commit hecho en la rama dedicada a la solución de este error, la rama llamada auth-feature/fix-issue53.
