### ISSUE TITLE
Líneas de código que superan los 79 caracteres: Voting

### ISSUE THREAD

**Issue by antnolang** [decide-dialga/decide#70]
Es necesario un responsable del equipo que se encargue de refactorizar todo el módulo de Voting (y solo el módulo de Voting) para mantener una buena calidad del código para la siguiente métrica: 

Todas las líneas del código deben tener un máximo de 79 caracteres.

**Comment by antnolang** [comment]
@serortagu El commit c57496b no debería cerrar esta issue

**Comment by ferruipli** [comment]
Se crea nueva issue #100  para evitar que el commit `c57496b` cierre esta issue
