### ISSUE TITLE
Añadir lista de votaciones a la página Home del sistema

### ISSUE THREAD

**Issue by CavernaryBeast** [decide-dialga/decide#72]
### Facilitar acceso a votaciones
Para facilitar el acceso a las votaciones, ya que ahora solo podemos acceder a ellas mediante la introducción de una URL manualmente, se pretende implementar lo siguiente:

- Listado de votaciones abiertas disponible en la página principal del sistema

Esto conlleva acceder a los métodos implementados en el sistema, usar los métodos de listado disponibles, e introducir las votaciones obtenidas mediante estos métodos en la vista.

**Comment by SiiNerGia** [comment]
Me adjunto a esta issue
